version: '3.7'

services:
  react:
    container_name: react
    tty: true
    restart: always
    build:
      context: ./reactApp
      dockerfile: Dockerfile
    volumes:
      - './reactApp:/reactApp'
      - '/reactApp/node_modules'
    ports:
      - '3002:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

  django:
    container_name: django
    tty: true
    restart: always
    build: 
      context: './djangoProject'
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './djangoProject:/djangoProject'
    ports:
      - "8000:8000"
