version: '3.7'

services:
  world:
    container_name: world
    tty: true
    restart: always
    build:
      context: ./world
      dockerfile: Dockerfile
    volumes:
      - './world:/world'
      - '/world/node_modules'
    ports:
      - '3002:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

  django:
    container_name: django
    tty: true
    restart: always
    build: 
      context: './djangoProject'
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './djangoProject:/djangoProject'
    ports:
      - "8000:8000"
